### PR TITLE
[MRG] Make execution_time adaptable

### LINKED ISSUE #26: Phase and forcing_term are not updated inside dmp_open_loop()
First of all thank you for sharing this great repo. It has helped me a lot to understand the theory behind DMPs.

I have been doing some experiments with your code and when changing the run_t to a different value from the original execution_time I have detected that the algorithm does not correctly adapt to the new run_t.

If run_t < execution time, the movement does not adapt and it is like the result is cut. If run_time > execution time, during that extra time the last position is kept.

I think the problem is that the phase and forcing_terms are not updated inside [dmp_open_loop](https://github.com/dfki-ric/movement_primitives/blob/b1b231c23a93a49150628ecf15af3a5d6f1ca199/movement_primitives/dmp/_dmp.py#L402). It is not done either in [dmp_step_euler](https://github.com/dfki-ric/movement_primitives/blob/b1b231c23a93a49150628ecf15af3a5d6f1ca199/movement_primitives/dmp/_dmp.py#L178).

I have tried to fix it myself with no luck, because I completely loose the shape of the resulting curve. 

Could you help me with this?

### PR DESCRIPTION
**Pull request by AlexanderFabisch**
Fixes #26

### CODE REVIEW

**Comment by ilska** [comment]
It works now :) 
Figure_2

Ok, I think I understand now the changes you have made. If I do similar changed to the [CartesianDMP](https://github.com/dfki-ric/movement_primitives/blob/9ddacd41677b3521e9a8f8b9a9ca927aab9ce5c0/movement_primitives/dmp/_cartesian_dmp.py#L136) class, do you think I can achieve the same behaviour for both position and orientation?

**Comment by AlexanderFabisch** [comment]
I am working on this already. I'll let you know as soon as it is available on this branch. However, it will take some time to merge, because it also affects other DMP types and has to be tested properly.

**Comment by ilska** [comment]
Cool, thanks!

**Comment by AlexanderFabisch** [comment]
It works for Cartesian DMPs with the last commit.

**Comment by ilska** [comment]
Tested and it works for me too. Thank you for your time! Your repo has really helped me understanding the DMPs

**Pull request merged**
